### ISSUE TITLE
LESS relevance

### ISSUE THREAD

**Issue by gjuchault** [RebirthDB/electron-admin#1]
It seems that LESS is becoming less and less used (no pun intended), and maybe postcss should be enough. I should mention SASS, but it's a bit annoying to download an executable to get it running.

There are also a "ton" of JS solutions (styled components ?)

**Comment by thelinuxlich** [comment]
+1 for postcss

**Comment by oferitz** [comment]
All the cool kids using CSS in JS now (Emotion, glamorous, styled  components etc.) i'll be happy to jump on this wagon. having said that i do see one advantage in using LESS which is the ability to leverage the Awesome https://ant.design/docs/react/introduce components which IMHO is the best React components out there and they are using LESS and in order to customize it you need LESS.

**Comment by chovy** [comment]
I vote for scss. it just works and there's a native npm module now, you don't need to install gem.

**Comment by sagivf** [comment]
+1 for styled components. But I'm for using what ever the main contributor prefers on matters that are not critical or hard to learn (like choice of framework or language).

**Comment by gjuchault** [comment]
Indeed antd would be quite helpful to get a UI fast (which is important indeed).
`emotion.sh` is getting a huge approval from the community indeed. I'm in for antd + emotion if that's still possible

**Comment by oferitz** [comment]
@gjuchault Agreed! Would you like to kick it off?
For reference [here](http://react-component.github.io/badgeboard/) is the list of antd components that can be used separately without relaying on the antd library.

**Comment by phillx** [comment]
i vote for SCSS or better : styled-components/styled-components

**Comment by oferitz** [comment]
As i see it we have 2 possible paths here:

1. Preprocessors: SCSS or LESS. In this case i prefer going with LESS for better compatibility with our React components library of choice [(antd)](https://ant.design/docs/react/introduce)

2. CSS in JS (Emotion, glamorous, styled components etc.) which seems to be the direction that the community is currently going to. 

For me part of participating in this is the chance to learn some new stuff. So what i'm suggesting is to go with the second option for now and see how it's going, if we see that it causing us pain, slowing us down or preventing us to focus on the important stuff (deliver a robust client fast) than we can change back to the more familiar tools.

So if no one has objection i'm going to close this issue.

**Comment by gjuchault** [comment]
@phillx I think emotion is a form of styled components :)
@oferitz Agree with your last post. I've not used css in js production, so I can't really suggest how we structure the directory. https://github.com/styled-components/styled-components/issues/650 seems to give some answers, what do you think ?

**Comment by Rizary** [comment]
vote for scss.

**Comment by oferitz** [comment]
@gjuchault Both options that Max Stoiber wrote there are a good start just pick one :)
You can also take a look at [spectrum.chat](https://github.com/withspectrum/spectrum) and [action](https://github.com/ParabolInc/action/tree/master/src) source code to see how they structure things. 
Personally i tend to go with one file per component approach.

**Comment by thelinuxlich** [comment]
Whatever is more fun to use :D

**Comment by oferitz** [comment]
@gjuchault go for it, it's a good start.

**Comment by gjuchault** [comment]
You may find a PR here: https://github.com/RebirthDB/electron-admin/pull/2
What do you think of it ?

**Comment by oferitz** [comment]
@gjuchault i'm checking it now and closing this issue.
